config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root "pages#index"
  
  get "about"        =>    "pages#about"
  
  get "courses"      =>    "courses#index"

  
  
  
  
  
  

end

app/models/course.rb
class Course < ActiveRecord::Base

    has_attached_file :image, styles: { medium: "300x300#", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/



end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    http_basic_authenticate_with name: ENV.fetch("ADMIN_NAME"), password: ENV.fetch("ADMIN_PASSWORD")
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Course.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Course.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController


  def index
      @courses = Course.all
  
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  def index
    # render text: "Hello world !"
  end
  
  
  
  def about
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/index.html.erb
<h1><%= @courses.count%>  Courses available ! </h1>

<hr/>

<div class="row">

        <% @courses.each do |course| %>
        
        
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <%= image_tag course.image.url(:thumb), alt: course.title %>      
                <div class="caption">
                    <h3><%= course.title %></h3>
                    <p> <%= course.description%> </p>
                    <p><a href="#" class="btn btn-primary" role="button">Visionner le cours</a>
              </div>
            </div>
          </div>
          
              <% end %>
</div>

   

app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.medium %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  

  
  
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  
  
  
  
  
  
</head>

<body>

  <%= render "layouts/partials/nav"  %>

  <div class="container" id="content">
  
    <%= yield %>
    
    <%= render "layouts/partials/footer"  %>
    
  </div>





</body>

</html>

app/views/layouts/partials/_footer.html.erb
<footer id="main-footer">
  
  <p> Built with Ruby on Rails : &copy 2015 - All Rights Reserved </p>
  
  
</footer>

app/views/layouts/partials/_nav.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" id="main-menu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Online Courses App", root_path, class:"navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
                <li> <%= link_to "Courses", courses_path %></li>
                <li><%= link_to "About", about_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/pages/about.html.erb
<h1> About</h1>


<p> Exemple test</p>

app/views/pages/index.html.erb
<div class="jumbotron">


    <h1>  Hello !</h1>
        
    <br/>
        
    <p> Bienvenue  sur ce site de cours en ligne ! </p>


</div>